- name: Setup Redis Server
  hosts:
    - server_role_redis_server
  become: true
  gather_facts: yes # Collect facts only once for the entire play
  vars:
    ansible_user: "{{ 'rocky' if 'server_role_redis_server' in group_names else 'admin' }}"
  roles:
    - rocky
- name: Setup Frontend Servers
  hosts:
    - server_role_frontend_server
  become: true
  gather_facts: yes # Collect facts only once for the entire play
  roles:
    - debian


